language: go
arch:
  - amd64
  - ppc64le
sudo: false
go_import_path: golang.org/x/tools/cmd/vet/
go:
  - 1.5
  - tip

install:
  - go get -v golang.org/x/tools/cmd/vet
  - go get -v golang.org/x/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...

script:
  - go vet ./...
  - golint .
  - go test -v -parallel=8 ./...
