language: go
arch:
  - amd64
  - ppc64le
##sudo: false
go_import_path: golang.org/x/tools/cmd/vet/
go_import_path: golang.org/x/tools/go/gcexportdata/
go:
  - 1.10
  - tip

install:
  - go get -v golang.org/x/tools/cmd/vet
  - sudo go get -v golang.org/x/lint/golint
  - sudo go get -d -t -v ./...
  - sudo go build -v ./...

script:
  - sudo go vet ./...
  - sudo golint .
  - go test -v -parallel=8 ./...
